baseURL = "https://www.beautyhydration.com/"
languageCode = "en-us"
title = "Beauty Hydration"
summaryLength = 25
[[menu.main]]
name = "Ailment"
parent = "IV Hydration"
weight = 2
[[menu.main]]
name = "Fillers"
parent = "Beauty"
weight = 2
[[menu.main]]
name = "Wellness"
parent = "IV Hydration"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[[menu.main]]
name = "Injections"
weight = 4
[[menu.main]]
name = "IV Hydration"
weight = 3
[[menu.main]]
name = "Beauty"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
tag = "tags"
collection = "collections"
product-tag = "product-tags"
