baseURL = "https://beautyhydration.netlify.app/"
languageCode = "en-us"
title = "Beauty Hydration"
[[menu.main]]
name = "Home"
url = "/"
weight = 5
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 15