---
label: Service
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: banner_image
  type: file
  config:
    maxSize: 64
  label: Banner Image
- name: service_list
  type: field_group_list
  fields:
  - name: heading
    type: text
    config:
      required: false
    label: Heading
  - name: body_text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Body Text
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
  config:
    min: 
    max: 
    labelField: 
  label: Service List
- name: price_heading
  type: text
  config:
    required: false
  label: Price Heading
- name: price_subtitle
  type: text
  config:
    required: false
  label: Price Subtitle
- name: price
  type: text
  config:
    required: false
  label: Price
